Repository googleapis/java-accesscontextmanager, pull requests merged in 2021-08, with the labels that each got.

#213 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, api: accesscontextmanager, context: full

#221 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: accesscontextmanager

#226 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: automerge, kokoro:force-run, cla: yes, api: accesscontextmanager, context: full

#232 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: accesscontextmanager
