Repository googleapis/java-accesscontextmanager, pull requests merged in 2021-05, with the labels that each got.

#187 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: accesscontextmanager, automerge, cla: yes, context: none

#188 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: accesscontextmanager, automerge, cla: yes

#189 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: accesscontextmanager, automerge, cla: yes, context: full

#191 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: accesscontextmanager, automerge, cla: yes, context: full

#192 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: accesscontextmanager, automerge, cla: yes, context: full

#194 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: accesscontextmanager, automerge, cla: yes, context: full

#196 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: accesscontextmanager, automerge, cla: yes, context: full
